version: 2
jobs:
  test_sentiment_analysis:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/sentiment_analysis/requirements.txt
            #chmod +x ./scripts/fetch_kaggle_dataset.sh
            #./scripts/fetch_kaggle_dataset.sh
            py.test -vv packages/sentiment_analysis/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_sentiment_analysis
